# Generated by Django 4.1.5 on 2023-02-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misa',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='misa',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
