# Generated by Django 4.1.5 on 2023-02-04 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_alter_misa_observaciones_alter_misa_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
