# Generated by Django 4.1.5 on 2023-02-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0003_cronograma_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='mes_año',
            new_name='cronograma',
        ),
    ]
